### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by nestorara** [nestorara/kcloud-music-api#1]
## Up Next

- [ ] Add debug mode
- [ ] Rename generated url to use the same domain of API or custom domain

## Done

- [x] Managament files to upload is too large when file is greater than 2GIB
- [x] Rename createsongSchema to songSchema, make all properties optional and repair code to valida succesfully the req.body
- [x] Delete posibility to update songFile
- [x] Rename types_and_interfaces to type
- [x] Not update cover directly via pass the string
- [x] Delete UploadFIles and deleteFiles function
- [x] Delete management multi errors in s3 funtions
- [x] Check if file fields is not repited before any operation with the song
- [x] Customize message when delete file for a message that inform if the song is deleted or not and if a one or more files could not be delete but song is succesfully delete
- [x] Delete repetition of boolean succes when getting url of a song or cover
- [x] Delete console.error or console.log not used or unnecesary, add consolo.error in corresponding controllers and replace consolo.log to console.error
- [x] Delete succes property in results and error and all management error code in try catch remplacing code with handleControllersError function
- [x] FIlter output private data, ej: AccountId, songFIle, Cover
- [x] Make maxFileSize a env
- [x] Check when pass the same field mora than 1 time (no file fields))
- [x] Covert errorCodes object to enum for restrinc and control errorCodes
- [x] Check if file exist in geturl
- [x] Implement fileExist in downloadFIle funtion
- [x] Manage errors connections and timeouts with s3
- [x] Delete IResult
- [x] Change name e to error in catch bloq
- [x] Delete none error
- [x] Repair error S3ServiceUnavilable not show to the client
- [x] Reparar check file exist in getFileURL function
- [x] Delete generateDataValidationResponseError function
- [x] Remplaze errors using classes that extend the javascript error class
- [x] Add posbility to add action and resource properties for all errors classes
- [x] Often show timeout error when storage server is working (The time must be specified in miliseconds)
- [x] Delete obsoleted errors and error codes
- [x] Create new Error when model in database not found
- [x] Add management error to DB
- [x] Customize some mongoose functions
- [x] Rename resource to resoureName for clarity
- [x] Add posibility to use .env file
- [x] Personalice 404 error page and another codes
- [x] Verify if cover is a image and song an audio
- [x] Add posibility to dowload song or cover
- [x] FIlter the created song directly and avoid call 2 times to Database
- [x] fix error when sometimes a song is created, it returns an error song not found
